ALTER TABLE IF EXISTS stands
  ADD COLUMN IF NOT EXISTS species TEXT,
  ADD COLUMN IF NOT EXISTS management_type TEXT,
  ADD COLUMN IF NOT EXISTS age_class TEXT,
  ADD COLUMN IF NOT EXISTS altitude_m DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS notes TEXT;
